export const constantsApp = {
	//RUTAS
	ROUTE_POSTS: '/',
	ROUTE_ERROR: '/error',

	//ACCIONES A EJECUTAR EN EL CRUD
	ACTION_CREATE: 'crear',
	ACTION_EDIT: 'editar',

	//ENDPOINTS
	ENDPOINT_LANG_ES: 'data/lang-es.json',

	//COLLECTIONS FIRESTORE
	COLLECTION_POST: 'post-test',
	COLLECTION_COMMENTS: 'comments',
	COLLECTION_REACTIONS: 'reactions',
	COLLECTION_USERS: 'users',

	//REACTIONS
	REACTION_LIKE: 'like',
	REACTION_DISLIKE: 'dislike',
	REACTION_AMAZING: 'amazing',

	//PROPIEDA PARA VALIDAR LOGIN
	IS_LOGGED: 'isLoggedIn'
};
